version: '3.4'
name: template-api
services:
  template.api:
    image: ${DOCKER_REGISTRY-}templateapi
    container_name: Template.API
    build:
      context: .
      dockerfile: Template.Api/Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  core-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Core.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Strong_password_123!"
